### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by dylanaraps** [dylanaraps/saxandfish#1]
- [x] Fix z-index of nav background
- [x] Fix footer on ie11
- [x] Use icon for hamburger menu
- [x] Make the images smaller
- [x] Fix footer padding on Chromium
- [x] Fix z-index issues
- [ ] Move some common areas (nav, footer, etc) to templates for future use
- [ ] Finish about me and contact us pages
- [ ] Remove all lorem ipsum
- [ ] Look into more optimization.
- [x] Fix mobile viewport issue(?)
- [x] Compress images further
- [x] Cleanup scss and reduce nesting amount
- [x] Fix browser-sync scroll

Later:
- [ ] Move the site to apache server
- [ ] Create a `.htaccess` file
- [ ] Create a `robots.txt` file
- [ ] Create a `sitemap.xml` file
